### ISSUE TITLE
Likely problem

### ISSUE THREAD

**Issue by oliveiradev** [hhariri/oreilly-kotlin-course#1]
Inside file `Inheritance.kt` in line 30, has one likely error, data class can not extend other classes only implement.

Documentation stretch:
`-Data classes may not extend other classes (but may implement interfaces).`

**Comment by hhariri** [comment]
@oliveiradev The documentation refers to 1.0 it seems and most likely not updated. The course is covering 1.1 which includes this change.

**Comment by oliveiradev** [comment]
Sory for my bad @hhariri , I saw that today.
