### ISSUE TITLE
Excellent source of Learning Kotlin

### ISSUE THREAD

**Issue by cyrsis** [hhariri/oreilly-kotlin-course#3]
Everything you teach is great, specially for C# developer, I just happen to have tough time get intellij idea load up the project, if I create a new one with Kotlin, everything runs great

**Comment by hhariri** [comment]
Thank you! Which projects are these?

**Comment by cyrsis** [comment]
"intro" in oreilly-kotlin-course

The "advanced" works fine with gradle. But kind of lose for setup the run config

Just moved to kotlin + ideas from C# + resharper

When I open "C:\Dev\oreilly-kotlin-course\intro"

Then Edit Config -> "Kotlin" -> Main Class: MainKt

Error Class "MainKt" not found in module intro

**Comment by hhariri** [comment]
I've made some fixes and checked in the module files. See if that helps.
