### ISSUE TITLE
cannot find CustomerJava file, classes folder appears to be missing

### ISSUE THREAD

**Issue by jrmineur** [hhariri/oreilly-kotlin-course#4]
Love the O'Reilly course on Kotlin!   Thank you for your instruction - I am finding it most helpful to dive into Kotlin development.

There is one thing I can't find - the CustomerJava file.   In looking for it - it looks like the classes folder isn't present in the repo - all the other folders seem to be there

    oreilly-kotlin-course/intro/src/com/hadihariri/kotlincourse/   (no classes folder!)

Mostly I am typing in my own version of what you are teaching - so this is the first time that I was looking to leverage something straight from the repo...

Thanks again!

**Comment by jrmineur** [comment]
One update - I was able to create the CustomerJava.java file by converting the following single line of Kotlin code to Java:

    data class CustomerJava(val id: Int, val name: String, val email: String) {}

I followed the instructions at [http://stackoverflow.com/a/40762755/3853712](http://stackoverflow.com/a/40762755/3853712) to go from Kotlin Bytecode and then to Java.   As you have already shown in the videos, one gets a LOT of Java from one line of Kotlin in this case!!   I entered the CustomerJava.java into a Github Gist here:   

https://gist.github.com/jrmineur/f17108981d6d761a2ec8ce05dc59eb67

Thanks again for your wonderful job of teaching Kotlin!

**Comment by hhariri** [comment]
Hi. Sorry about that. Thank you, glad it's helping. I'll fix it (or please feel free to send me a PR :)

**Comment by hhariri** [comment]
I've fixed this and will be in 1.1.3 branch
